name: Deploy to server

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-deploy-via-sftp:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      FILES_TO_COPY: ./build/*
      REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: 20
        run: |
          npm install
          npm run build
      - name: Deploy
        run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete $FILES_TO_COPY $USERNAME@$SERVER_IP:$REMOTE_PATH
        working-directory: ./
